# Generated by Django 4.1.2 on 2022-10-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_status', models.CharField(blank=True, choices=[('Reached the router', 'Reached the router'), ('Reached the receiver', 'Reached the receiver')], default='Reached the router', max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
