# Generated by Django 4.1.2 on 2022-10-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sender_uuid',
            new_name='transaction_uuid',
        ),
    ]
