# Generated by Django 4.1.2 on 2022-10-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_sender_uuid_transaction_transaction_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
